[package]
name = "exchanges"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "exchanges"

[dependencies]
utils = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
exchanges_integrity = { workspace = true }