[package]
name = "mediums_of_exchange"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "mediums_of_exchange"

[dependencies]
utils = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
mediums_of_exchange_integrity = { workspace = true }
