[package]
name = "requests_integrity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "requests_integrity"

[dependencies]
utils = { workspace = true }
hdi = { workspace = true }
serde = { workspace = true }
