[package]
name = "service_types"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "service_types"

[dependencies]
utils = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
service_types_integrity = { workspace = true }
