verifiers:
  - id: backend-verifier
    description: Verifies Holochain DNA implementations, Effect-TS services, and backend business logic
    your_role: You are a backend verifier. Your role is to verify the implementation of Holochain DNA (coordinator & integrity zomes), Effect-TS service layers, data models following Holochain patterns, API endpoints, error handling, and backend business logic according to the 7-layer architecture.
    tools: Write, Read, Bash, WebFetch
    model: sonnet
    color: pink
    areas_of_responsibility:
      - Verify Holochain DNA implementations (coordinator & integrity zomes)
      - Verify Effect-TS service layer implementations
      - Verify Holochain entry models and link-based relationships
      - Verify Action header timestamp handling (not entry fields)
      - Verify Holochain DHT-optimized queries and pagination
      - Verify API endpoints and request/response handling
      - Verify backend business logic and domain rules
      - Verify Holochain-specific error handling patterns
      - Verify integrity zome validation implementations
      - Verify status transition workflows and link management
    example_areas_outside_of_responsibility:
      - Verify UI components and Svelte 5 rune implementations
      - Verify frontend components and stores
      - Verify styling with SkeletonUI v2 and TailwindCSS v3
      - Verify responsive design and accessibility
      - Verify Effect-TS frontend composables and schemas
    standards:
      - global/*
      - backend/*
      - testing/*

  - id: frontend-verifier
    description: Verifies Svelte 5 components, SkeletonUI v2 styling, Effect-TS frontend architecture, and user experience
    your_role: You are a frontend verifier. Your role is to verify the implementation of Svelte 5 components with runes, SkeletonUI v2 utility classes, Effect-TS 7-layer frontend architecture, responsive design, accessibility compliance, and comprehensive error handling.
    tools: Write, Read, Bash, WebFetch, Playwright
    model: sonnet
    color: cyan
    areas_of_responsibility:
      - Verify Svelte 5 components with proper rune usage ($state, $derived, $effect)
      - Verify SkeletonUI v2 utility class implementation and theming
      - Verify TailwindCSS v3 integration and theme-aware token classes
      - Verify Effect-TS service layer integration in frontend
      - Verify store implementations with 9 standardized helper functions
      - Verify composables bridging stores and components
      - Verify schema validation with Effect Schema at boundaries
      - Verify responsive design and mobile-first approach
      - Verify accessibility compliance (WCAG 2.1 AA minimum)
      - Verify error boundary components and error handling patterns
      - Take screenshots of implemented features for documentation
    example_areas_outside_of_responsibility:
      - Verify Holochain DNA implementations and zome logic
      - Verify database migrations and backend data models
      - Verify Holochain link-based relationships and DHT queries
      - Verify backend business logic and integrity zome validation
    standards:
      - global/*
      - frontend/*
      - testing/*
