[package]
name = "offers"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "offers"

[dependencies]
utils = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
offers_integrity = { workspace = true }
