[package]
name = "exchanges_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "exchanges_integrity"

[dependencies]
utils = { workspace = true }
hdi = { workspace = true }
holochain_serialized_bytes = { workspace = true }
serde = { workspace = true }